version: '3'
services:
  tk-integration-auth:
    image: spannozzo/tk-integration-auth-native:latest
    build: 
      context: ./tk-integration-auth/
      dockerfile: ./src/main/docker/Dockerfile.native
    container_name: "tk-integration-auth"
    environment:
      - smallrye.jwt.sign.key-location=/META-INF/resources/privatekey.pem
      - mp.jwt.verify.publickey.location=/META-INF/resources/publickey.pem
      - mp.jwt.verify.duration=25
      - quarkus.http.port=8080
    networks:
      - tk-integration-network
  tk-integration-fu:
    image: spannozzo/tk-integration-fu-native:latest
    build: 
      context: ./tk-integration-fu/
      dockerfile: ./src/main/docker/Dockerfile.native
    container_name: "tk-integration-fu"
    environment:
      - quarkus.http.port=8080
      - smallrye.jwt.sign.key-location=/META-INF/resources/privatekey.pem
      - mp.jwt.verify.publickey.location=/META-INF/resources/publickey.pem
      - auth.url=http://tk-integration-auth:8080/accesstoken
      - cv-store-folder=./
    # volumes:
     # - ./stored-cvs:/stored-cvs
    depends_on:
      - "tk-integration-auth"
    networks:
      - tk-integration-network
  tk-integration-main:
    image: spannozzo/tk-integration-main-native:latest
    build: 
      context: ./tk-integration-main/
      dockerfile: ./src/main/docker/Dockerfile.native
    container_name: "tk-integration-main"
    environment:
      - smallrye.jwt.sign.key-location=/META-INF/resources/privatekey.pem
      - mp.jwt.verify.publickey.location=/META-INF/resources/publickey.pem
      - quarkus.http.ssl.certificate.file=META-INF/resources/cert.pem
      - quarkus.http.ssl.certificate.key-file=META-INF/resources/key.pem
      - quarkus.http.ssl-port=8443
      - quarkus.http.port=8081
      - auth.url=http://tk-integration-auth:8080/accesstoken
      - fu.url=http://tk-integration-fu:8080/
    ports:
      - "8443:8443"
    expose:
      - "8443"
    depends_on:
      - "tk-integration-fu"
      - "tk-integration-auth"
    networks:
      - tk-integration-network
networks:
  tk-integration-network:
    external: false 
    

  